/**
 * Adapter fidelity against recorded, device-shaped fixtures.
 *
 * The other adapter suites hand-build the objects they feed in, which means
 * they can only ever prove the adapter handles what the test author thought
 * of. These fixtures (`src/testing/fixtures/`, generated by
 * `scripts/generate-device-fixtures.mjs`) instead carry the whole surface a
 * real capture produces — a Muse-class BLE frame with every block populated,
 * an rppg-web `Metrics` object with every field set, a ppg-web `PpgMetrics`
 * emission — and the adapters are driven from them end to end into committed
 * Arrow chunks.
 *
 * The suite also reads the peer packages' own type declarations and fails
 * when they grow a field the SDK does not map. That is the point: a metric
 * added upstream that quietly never reaches storage is a data-loss bug that
 * no amount of hand-built fixtures would surface.
 */

import * as fs from "node:fs";
import * as path from "node:path";
import type {
	HeadbandFrameV1,
	HeadbandTransport,
} from "@elata-biosciences/eeg-web";
import type { PpgMetrics } from "@elata-biosciences/ppg-web";
import type { Metrics } from "@elata-biosciences/rppg-web";
import { createHeadbandSource } from "../adapters/headbandSource";
import { createPpgSource, ppgMetricsToRow } from "../adapters/ppgSource";
import { createRppgSource, rppgMetricsToRow } from "../adapters/rppgSource";
import type { SourceSink, StreamHandle } from "../adapters/types";
import { decodeChunk, readFloat32Column } from "../arrow/decode";
import {
	ppgMetricsSchema,
	rppgMetricsSchema,
	type ChunkIdentity,
} from "../arrow/schemas";
import type {
	ClockObservationDraft,
	SessionEventDraft,
	StreamDescriptorDraft,
} from "../contracts/session";
import { createRecorderHarness } from "../testing/recorderHarness";

// ---------------------------------------------------------------------------
// Fixtures
// ---------------------------------------------------------------------------

const fixturesDir = path.resolve(__dirname, "..", "testing", "fixtures");

function loadFixture<T>(name: string): T {
	return JSON.parse(fs.readFileSync(path.join(fixturesDir, name), "utf8")) as T;
}

interface FixtureFile<T> {
	fixtureVersion: number;
	sourcePackage: string;
	sourceType: string;
	capture: Record<string, unknown> & { fullSurfaceIndex?: number };
}

const headbandFixture = loadFixture<
	FixtureFile<never> & { frames: HeadbandFrameV1[] }
>("headband-frames-v1.json");
const rppgFixture = loadFixture<FixtureFile<never> & { metrics: Metrics[] }>(
	"rppg-metrics-v1.json",
);
const ppgFixture = loadFixture<FixtureFile<never> & { metrics: PpgMetrics[] }>(
	"ppg-metrics-v1.json",
);

const FRAMES = headbandFixture.frames;
const RPPG_METRICS = rppgFixture.metrics;
const PPG_METRICS = ppgFixture.metrics;
const FULL_RPPG = RPPG_METRICS[rppgFixture.capture.fullSurfaceIndex ?? 0];
const FULL_PPG = PPG_METRICS[ppgFixture.capture.fullSurfaceIndex ?? 0];

// ---------------------------------------------------------------------------
// Upstream type surface (read from the peer packages, not restated here)
// ---------------------------------------------------------------------------

/** Read a peer package's TypeScript source out of the workspace. */
function peerSource(packageDir: string, file: string): string {
	const resolved = path.resolve(
		__dirname,
		"..",
		"..",
		"..",
		packageDir,
		"src",
		file,
	);
	if (!fs.existsSync(resolved)) {
		throw new Error(
			`peer source not found at ${resolved} — these tests read the real ` +
				"type declarations and must run inside the monorepo",
		);
	}
	return fs.readFileSync(resolved, "utf8");
}

interface DeclaredMember {
	name: string;
	type: string;
}

/**
 * Top-level members of `export type X = {…}` / `export interface X {…}`.
 * Members are matched at exactly one tab of indentation, so nested object
 * literals do not leak in.
 */
function declaredMembers(source: string, typeName: string): DeclaredMember[] {
	const declaration = new RegExp(
		`export (?:type ${typeName} = \\{|interface ${typeName} \\{)`,
	).exec(source);
	if (!declaration) throw new Error(`type not found upstream: ${typeName}`);
	const open = source.indexOf("{", declaration.index);
	let depth = 0;
	let end = -1;
	for (let i = open; i < source.length; i++) {
		if (source[i] === "{") depth++;
		else if (source[i] === "}") {
			depth--;
			if (depth === 0) {
				end = i;
				break;
			}
		}
	}
	if (end < 0) throw new Error(`unterminated declaration: ${typeName}`);
	const members: DeclaredMember[] = [];
	for (const line of source.slice(open + 1, end).split("\n")) {
		const match = /^\t(\w+)\??:\s*(.+?);?\s*$/.exec(line);
		if (match) members.push({ name: match[1], type: match[2] });
	}
	if (members.length === 0) throw new Error(`no members parsed: ${typeName}`);
	return members;
}

const headbandSource = peerSource("eeg-web", "headband.ts");
const rppgSourceText = peerSource("rppg-web", "rppgProcessor.ts");
const ppgSourceText = peerSource("ppg-web", "ppgProcessor.ts");

const FRAME_MEMBERS = declaredMembers(headbandSource, "HeadbandFrameV1");
const PROCESSING_FIELDS = declaredMembers(
	headbandSource,
	"HeadbandEegProcessingDetails",
).map((member) => member.name);
const RPPG_FIELDS = declaredMembers(rppgSourceText, "Metrics").map(
	(member) => member.name,
);
const PPG_FIELDS = declaredMembers(ppgSourceText, "PpgMetrics").map(
	(member) => member.name,
);

/** Frame members that carry samples, and therefore must become a stream. */
const BLOCK_MEMBERS = FRAME_MEMBERS.filter((member) =>
	/HeadbandSignalBlock|HeadbandBatteryBlock/.test(member.type),
).map((member) => member.name);

/** The mapping this SDK implements, restated so drift is visible in a diff. */
const BLOCK_TO_MODALITY: Record<string, string> = {
	eeg: "eeg",
	eegRaw: "eeg-raw",
	ppgRaw: "ppg",
	optics: "optics",
	accgyro: "imu",
	battery: "battery",
};

const snakeCase = (name: string): string =>
	name.replace(/([a-z0-9])([A-Z])/g, "$1_$2").toLowerCase();

const IDENTITY: ChunkIdentity = {
	sessionId: "s",
	streamId: "t",
	arrowSchemaId: "rppg-metrics@1",
};

// ---------------------------------------------------------------------------
// Capture sink (adapter-level observations)
// ---------------------------------------------------------------------------

interface Captured {
	sink: SourceSink;
	nowUs: { value: number };
	opened: StreamDescriptorDraft[];
	pushes: {
		modality: string;
		data: Float32Array;
		rows: number;
		sampleIndex0: number;
		timeUs0: number;
	}[];
	irregular: { modality: string; timesUs: Float64Array; data: Float32Array }[];
	hints: { modality: string; reason: string }[];
	events: SessionEventDraft[];
	observations: ClockObservationDraft[];
}

function captureSink(): Captured {
	const nowUs = { value: 0 };
	const captured: Captured = {
		nowUs,
		opened: [],
		pushes: [],
		irregular: [],
		hints: [],
		events: [],
		observations: [],
		sink: {
			clock: { nowUs: () => nowUs.value },
			openStream(draft): StreamHandle {
				captured.opened.push(draft);
				return {
					streamId: `${draft.modality}-id`,
					pushRegular(rowMajor, rows, sampleIndex0, timeUs0) {
						captured.pushes.push({
							modality: draft.modality,
							data: rowMajor.slice(),
							rows,
							sampleIndex0,
							timeUs0,
						});
					},
					pushIrregular(timesUs, rowMajor) {
						captured.irregular.push({
							modality: draft.modality,
							timesUs: timesUs.slice(),
							data: rowMajor.slice(),
						});
					},
					pushMetricRow() {},
					hintDiscontinuity(reason) {
						captured.hints.push({ modality: draft.modality, reason });
					},
					close() {},
				};
			},
			event(event) {
				captured.events.push(event);
			},
			clockObservation(observation) {
				captured.observations.push(observation);
			},
			status() {},
		},
	};
	return captured;
}

function fakeTransport(): HeadbandTransport {
	return {
		onFrame: undefined,
		onStatus: undefined,
		connect: async () => {},
		disconnect: async () => {},
		start: async () => {},
		stop: async () => {},
	};
}

/** Replay the recorded frames at their real inter-frame spacing. */
async function replayFrames(
	deliver: (frame: HeadbandFrameV1) => void,
	advanceUs: (us: number) => void | Promise<void>,
): Promise<void> {
	let previousSequence: number | null = null;
	const frameUs = Math.round((FRAMES[0].eeg.samples.length * 1_000_000) / FRAMES[0].eeg.sampleRateHz);
	for (const frame of FRAMES) {
		if (previousSequence !== null) {
			// A dropped notification costs its own frame's worth of wall time.
			await advanceUs(frameUs * (frame.sequenceId - previousSequence));
		}
		previousSequence = frame.sequenceId;
		deliver(frame);
	}
}

// ---------------------------------------------------------------------------

describe("the fixtures still describe the upstream types", () => {
	it("carries every HeadbandFrameV1 member, including all six blocks", () => {
		expect(BLOCK_MEMBERS.slice().sort()).toEqual(
			Object.keys(BLOCK_TO_MODALITY).sort(),
		);
		const acrossFrames = new Set(FRAMES.flatMap((frame) => Object.keys(frame)));
		expect([...acrossFrames].sort()).toEqual(
			FRAME_MEMBERS.map((member) => member.name).sort(),
		);
		const details = FRAMES[0].eegProcessing;
		expect(details).toBeDefined();
		expect(Object.keys(details as object).sort()).toEqual(
			PROCESSING_FIELDS.slice().sort(),
		);
	});

	it("carries the full rppg-web Metrics and ppg-web PpgMetrics surfaces", () => {
		expect(Object.keys(FULL_RPPG).sort()).toEqual(RPPG_FIELDS.slice().sort());
		expect(Object.keys(FULL_PPG).sort()).toEqual(PPG_FIELDS.slice().sort());
		expect(FRAMES).toHaveLength(4);
		expect(RPPG_METRICS.length).toBeGreaterThanOrEqual(3);
		expect(PPG_METRICS.length).toBeGreaterThanOrEqual(3);
	});
});

describe("every upstream metric field reaches an Arrow column", () => {
	it("maps every rppg-web Metrics field onto rppg-metrics@1", () => {
		const columns = new Set(
			rppgMetricsSchema(IDENTITY).fields.map((field) => field.name),
		);
		const unmapped = RPPG_FIELDS.filter((field) => !columns.has(field));
		expect(unmapped).toEqual([]);
		// And the projection actually emits them all, from the real object.
		const row = rppgMetricsToRow(FULL_RPPG);
		expect(RPPG_FIELDS.filter((field) => !(field in row))).toEqual([]);
	});

	it("maps every ppg-web PpgMetrics field onto ppg-metrics@1", () => {
		const columns = new Set(
			ppgMetricsSchema({ ...IDENTITY, arrowSchemaId: "ppg-metrics@1" }).fields.map(
				(field) => field.name,
			),
		);
		const unmapped = PPG_FIELDS.filter(
			(field) => !columns.has(snakeCase(field)),
		);
		expect(unmapped).toEqual([]);
		const row = ppgMetricsToRow(FULL_PPG);
		expect(PPG_FIELDS.filter((field) => !(snakeCase(field) in row))).toEqual([]);
	});

	it("maps every HeadbandEegProcessingDetails field into stream provenance", async () => {
		const transport = fakeTransport();
		const captured = captureSink();
		await createHeadbandSource(transport).start(captured.sink);
		transport.onFrame?.(FRAMES[0]);
		const provenance = captured.opened[0].processing as Record<string, unknown>;
		expect(provenance.kind).toBe("eeg-processing");
		const missing = PROCESSING_FIELDS.filter((field) => !(field in provenance));
		expect(missing).toEqual([]);
		expect(provenance).toMatchObject(
			FRAMES[0].eegProcessing as unknown as Record<string, unknown>,
		);
	});
});

describe("headband frames → streams", () => {
	it("opens one stream per populated block, in the documented modality", async () => {
		const transport = fakeTransport();
		const captured = captureSink();
		const source = createHeadbandSource(transport);
		await source.start(captured.sink);
		await replayFrames(
			(frame) => transport.onFrame?.(frame),
			(us) => {
				captured.nowUs.value += us;
			},
		);

		expect(captured.opened.map((draft) => draft.modality)).toEqual([
			"eeg",
			"eeg-raw",
			"ppg",
			"optics",
			"imu",
			"battery",
		]);
		const byModality = new Map(
			captured.opened.map((draft) => [draft.modality, draft]),
		);
		expect(byModality.get("eeg")).toMatchObject({
			sampling: "regular",
			sampleRateHz: FRAMES[0].eeg.sampleRateHz,
			arrowSchemaId: "regular-wide-f32@1",
			clockSource: "device",
		});
		expect(byModality.get("eeg")?.channels.map((c) => c.name)).toEqual(
			FRAMES[0].eeg.channelNames,
		);
		expect(byModality.get("imu")?.channels.map((c) => c.name)).toEqual(
			FRAMES[0].accgyro?.channelNames,
		);
		expect(byModality.get("optics")?.sampleRateHz).toBe(
			FRAMES[0].optics?.sampleRateHz,
		);
		expect(byModality.get("battery")).toMatchObject({
			sampling: "irregular",
			arrowSchemaId: "battery@1",
		});
	});

	it("distinguishes processed eeg from the raw block on the same frame", async () => {
		const transport = fakeTransport();
		const captured = captureSink();
		await createHeadbandSource(transport).start(captured.sink);
		transport.onFrame?.(FRAMES[0]);
		const [processed, raw] = captured.opened;
		expect(processed.modality).toBe("eeg");
		expect(processed.processing).toMatchObject({
			applied: true,
			signalKind: "processed",
		});
		expect(raw.modality).toBe("eeg-raw");
		expect(raw.processing).toMatchObject({
			applied: false,
			signalKind: "raw",
			rawAvailable: true,
		});
		// The two blocks really do differ — the raw one still has its DC offset.
		const [processedPush, rawPush] = captured.pushes;
		expect(rawPush.data[0]).toBeGreaterThan(processedPush.data[0] + 500);
	});

	it("turns the dropped notification into a ble-reconnect discontinuity", async () => {
		const transport = fakeTransport();
		const captured = captureSink();
		await createHeadbandSource(transport).start(captured.sink);
		await replayFrames(
			(frame) => transport.onFrame?.(frame),
			(us) => {
				captured.nowUs.value += us;
			},
		);

		// Sequence 1043 never arrived: one gap event, hinted on every stream
		// that was open when the next frame landed.
		const gapEvents = captured.events.filter(
			(event) => event.name === "ble.sequence-gap",
		);
		expect(gapEvents).toHaveLength(1);
		expect(gapEvents[0]).toMatchObject({
			kind: "device-status",
			payload: { expected: 1043, actual: 1044 },
		});
		expect(new Set(captured.hints.map((hint) => hint.reason))).toEqual(
			new Set(["ble-reconnect"]),
		);
		expect(new Set(captured.hints.map((hint) => hint.modality))).toEqual(
			new Set(["eeg", "eeg-raw", "ppg", "optics", "imu"]),
		);
	});

	it("captures device timestamps as clock observations at the 10 s cadence", async () => {
		const transport = fakeTransport();
		const captured = captureSink();
		await createHeadbandSource(transport).start(captured.sink);

		transport.onFrame?.(FRAMES[0]);
		// One observation per device-clocked regular stream, on first sight.
		expect(captured.observations).toHaveLength(5);
		expect(captured.observations[0]).toMatchObject({
			kind: "device-clock",
			observedAtUs: 0,
			deviceTimestampMs: FRAMES[0].eeg.timestampsMs?.at(-1),
			sequenceId: FRAMES[0].sequenceId,
		});
		expect(new Set(captured.observations.map((o) => o.sourceId))).toEqual(
			new Set(["headband"]),
		);

		// Below the cadence: nothing more.
		captured.nowUs.value = 5_000_000;
		transport.onFrame?.(FRAMES[1]);
		expect(captured.observations).toHaveLength(5);

		// Past it: every device-clocked stream observes again.
		captured.nowUs.value = 10_000_000;
		transport.onFrame?.(FRAMES[2]);
		expect(captured.observations).toHaveLength(10);
		expect(captured.observations[5]).toMatchObject({
			observedAtUs: 10_000_000,
			deviceTimestampMs: FRAMES[2].eeg.timestampsMs?.at(-1),
			sequenceId: FRAMES[2].sequenceId,
		});
	});

	it("reports battery on its own irregular stream, not as a signal block", async () => {
		const transport = fakeTransport();
		const captured = captureSink();
		await createHeadbandSource(transport).start(captured.sink);
		captured.nowUs.value = 250_000;
		transport.onFrame?.(FRAMES[0]);
		expect(captured.irregular).toHaveLength(1);
		expect(Array.from(captured.irregular[0].data)).toEqual(
			FRAMES[0].battery?.samples,
		);
		expect(Array.from(captured.irregular[0].timesUs)).toEqual([250_000]);
		// Later frames carry no battery block, so nothing more is pushed.
		transport.onFrame?.(FRAMES[1]);
		expect(captured.irregular).toHaveLength(1);
	});
});

describe("recorded frames survive the whole pipeline", () => {
	it("lands every fixture sample, per channel, in the committed EEG chunk", async () => {
		const h = createRecorderHarness();
		const transport = fakeTransport();
		const source = createHeadbandSource(transport);
		await h.start({ sources: [source.descriptor()] });
		await h.startSource(source);

		const frameMs =
			(FRAMES[0].eeg.samples.length * 1000) / FRAMES[0].eeg.sampleRateHz;
		let previousSequence: number | null = null;
		for (const frame of FRAMES) {
			if (previousSequence !== null) {
				await h.advance(frameMs * (frame.sequenceId - previousSequence));
			}
			previousSequence = frame.sequenceId;
			transport.onFrame?.(frame);
			await h.settle();
		}
		h.core.handle({ t: "flush" });
		await h.settle();

		const eegStream = [...h.host.streams.values()].find(
			(stream) => stream.modality === "eeg",
		);
		expect(eegStream).toBeDefined();
		const chunks = h.host.chunksForStream(eegStream?.streamId as string);
		expect(chunks.length).toBeGreaterThan(0);

		const channels = FRAMES[0].eeg.channelNames;
		const decodedByChannel = new Map<string, number[]>(
			channels.map((name) => [name, []]),
		);
		let rows = 0;
		for (const chunk of chunks) {
			const table = decodeChunk(chunk.payload as Uint8Array).table;
			rows += table.numRows;
			for (const name of channels) {
				const column = readFloat32Column(table, name);
				decodedByChannel.get(name)?.push(...Array.from(column));
			}
		}
		expect(rows).toBe(FRAMES.length * FRAMES[0].eeg.samples.length);

		const expectedByChannel = channels.map((_name, channel) =>
			FRAMES.flatMap((frame) =>
				frame.eeg.samples.map((row) => Math.fround(row[channel])),
			),
		);
		channels.forEach((name, channel) => {
			expect(decodedByChannel.get(name)).toEqual(expectedByChannel[channel]);
		});

		// The dropped notification is recorded as a gap, not interpolated away —
		// once on every regular stream the frame carried, each counting the
		// samples that stream itself lost.
		const discontinuities = h.host.events.filter(
			(event) => event.kind === "discontinuity",
		);
		expect(discontinuities.map((event) => event.streamId).sort()).toEqual(
			[...h.host.streams.values()]
				.filter((stream) => stream.sampling === "regular")
				.map((stream) => stream.streamId)
				.sort(),
		);
		const eegGap = discontinuities.find(
			(event) => event.streamId === eegStream?.streamId,
		);
		expect(eegGap?.payload).toMatchObject({
			kind: "gap",
			reason: "ble-reconnect",
			missingSamples: FRAMES[0].eeg.samples.length,
		});
		// The 64 Hz optics stream loses its own three rows, not the EEG's twelve:
		// each stream's gap is counted in that stream's samples.
		const opticsStream = [...h.host.streams.values()].find(
			(stream) => stream.modality === "optics",
		);
		expect(
			discontinuities.find((event) => event.streamId === opticsStream?.streamId)
				?.payload,
		).toMatchObject({
			kind: "gap",
			reason: "ble-reconnect",
			missingSamples: FRAMES[0].optics?.samples.length,
		});
	});

	it("lands every rppg-web Metrics field in the committed chunk", async () => {
		const h = createRecorderHarness();
		let publish: ((metrics: Metrics) => void) | null = null;
		const source = createRppgSource({
			onMetrics: (callback) => {
				publish = callback;
				return () => {};
			},
			provenance: {
				kind: "rppg-processing",
				packageVersion: "0.14.0",
				trackerConfigId: "bpm-tracker-v1",
			},
		});
		await h.start({ sources: [source.descriptor()] });
		await h.startSource(source);
		for (const metrics of RPPG_METRICS) {
			publish?.(metrics);
			await h.advance(1_000);
		}
		h.core.handle({ t: "flush" });
		await h.settle();

		const stream = [...h.host.streams.values()].find(
			(candidate) => candidate.modality === "rppg-metrics",
		);
		expect(stream?.arrowSchemaId).toBe("rppg-metrics@1");
		const chunks = h.host.chunksForStream(stream?.streamId as string);
		const table = decodeChunk(chunks[0].payload as Uint8Array).table;
		expect(table.numRows).toBe(RPPG_METRICS.length);

		const rowIndex = rppgFixture.capture.fullSurfaceIndex ?? 0;
		for (const field of RPPG_FIELDS) {
			expectColumnMatches(table, field, rowIndex, FULL_RPPG[field as keyof Metrics]);
		}
		// A field the fixture leaves out reads as null, not as a stale value.
		expect(table.getChild("agreement")?.get(0)).toBeNull();
		expect(table.getChild("bayes_quality_provider_id")?.get(2)).toBeNull();
	});

	it("lands every ppg-web PpgMetrics field in the committed chunk", async () => {
		const h = createRecorderHarness();
		let publish: ((metrics: PpgMetrics) => void) | null = null;
		const source = createPpgSource({
			onMetrics: (callback) => {
				publish = callback;
				return () => {};
			},
		});
		await h.start({ sources: [source.descriptor()] });
		await h.startSource(source);
		for (const metrics of PPG_METRICS) {
			publish?.(metrics);
			await h.advance(1_000);
		}
		h.core.handle({ t: "flush" });
		await h.settle();

		const stream = [...h.host.streams.values()].find(
			(candidate) => candidate.modality === "ppg-metrics",
		);
		expect(stream?.arrowSchemaId).toBe("ppg-metrics@1");
		const chunks = h.host.chunksForStream(stream?.streamId as string);
		const table = decodeChunk(chunks[0].payload as Uint8Array).table;
		expect(table.numRows).toBe(PPG_METRICS.length);

		const rowIndex = ppgFixture.capture.fullSurfaceIndex ?? 0;
		for (const field of PPG_FIELDS) {
			expectColumnMatches(
				table,
				snakeCase(field),
				rowIndex,
				FULL_PPG[field as keyof PpgMetrics],
			);
		}
		expect(table.getChild("bpm")?.get(0)).toBeNull();
		expect(table.getChild("rmssd_ms")?.get(2)).toBeNull();
	});
});

/** Compare a decoded Arrow cell with the fixture value that produced it. */
function expectColumnMatches(
	table: ReturnType<typeof decodeChunk>["table"],
	column: string,
	row: number,
	expected: unknown,
): void {
	const vector = table.getChild(column);
	expect(vector).not.toBeNull();
	const actual = vector?.get(row);
	if (expected === null || expected === undefined) {
		expect(actual).toBeNull();
		return;
	}
	if (Array.isArray(expected)) {
		expect(Array.from(actual as Iterable<unknown>)).toEqual(expected);
		return;
	}
	if (typeof expected === "number") {
		// Metric columns are Float32/Int32/Float64 — compare at f32 precision.
		expect(Number(actual)).toBeCloseTo(expected, 3);
		return;
	}
	expect(actual).toEqual(expected);
}
