// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(eeg_ffiFFI)
import eeg_ffiFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_eeg_ffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_eeg_ffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate class UniffiHandleMap<T> {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt16: FfiConverterPrimitive {
    typealias FfiType = UInt16
    typealias SwiftType = UInt16

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt16 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterFloat: FfiConverterPrimitive {
    typealias FfiType = Float
    typealias SwiftType = Float

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Float {
        return try lift(readFloat(&buf))
    }

    public static func write(_ value: Float, into buf: inout [UInt8]) {
        writeFloat(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




/**
 * Alpha bump detector
 */
public protocol AlphaBumpDetectorProtocol : AnyObject {
    
    func minSamples()  -> UInt32
    
    func name()  -> String
    
    func process(interleavedData: [Float]) throws  -> AlphaBumpResult?
    
    func reset() 
    
    func setBaselineSmoothing(alpha: Float) 
    
    func setThreshold(multiplier: Float) 
    
}

/**
 * Alpha bump detector
 */
open class AlphaBumpDetector:
    AlphaBumpDetectorProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_eeg_ffi_fn_clone_alphabumpdetector(self.pointer, $0) }
    }
public convenience init(sampleRate: UInt16, channelCount: UInt32) {
    let pointer =
        try! rustCall() {
    uniffi_eeg_ffi_fn_constructor_alphabumpdetector_new(
        FfiConverterUInt16.lower(sampleRate),
        FfiConverterUInt32.lower(channelCount),$0
    )
}
    self.init(unsafeFromRawPointer: pointer)
}

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_eeg_ffi_fn_free_alphabumpdetector(pointer, $0) }
    }

    

    
open func minSamples() -> UInt32 {
    return try!  FfiConverterUInt32.lift(try! rustCall() {
    uniffi_eeg_ffi_fn_method_alphabumpdetector_min_samples(self.uniffiClonePointer(),$0
    )
})
}
    
open func name() -> String {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_eeg_ffi_fn_method_alphabumpdetector_name(self.uniffiClonePointer(),$0
    )
})
}
    
open func process(interleavedData: [Float])throws  -> AlphaBumpResult? {
    return try  FfiConverterOptionTypeAlphaBumpResult.lift(try rustCallWithError(FfiConverterTypeEegError.lift) {
    uniffi_eeg_ffi_fn_method_alphabumpdetector_process(self.uniffiClonePointer(),
        FfiConverterSequenceFloat.lower(interleavedData),$0
    )
})
}
    
open func reset() {try! rustCall() {
    uniffi_eeg_ffi_fn_method_alphabumpdetector_reset(self.uniffiClonePointer(),$0
    )
}
}
    
open func setBaselineSmoothing(alpha: Float) {try! rustCall() {
    uniffi_eeg_ffi_fn_method_alphabumpdetector_set_baseline_smoothing(self.uniffiClonePointer(),
        FfiConverterFloat.lower(alpha),$0
    )
}
}
    
open func setThreshold(multiplier: Float) {try! rustCall() {
    uniffi_eeg_ffi_fn_method_alphabumpdetector_set_threshold(self.uniffiClonePointer(),
        FfiConverterFloat.lower(multiplier),$0
    )
}
}
    

}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAlphaBumpDetector: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = AlphaBumpDetector

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> AlphaBumpDetector {
        return AlphaBumpDetector(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: AlphaBumpDetector) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AlphaBumpDetector {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: AlphaBumpDetector, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAlphaBumpDetector_lift(_ pointer: UnsafeMutableRawPointer) throws -> AlphaBumpDetector {
    return try FfiConverterTypeAlphaBumpDetector.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAlphaBumpDetector_lower(_ value: AlphaBumpDetector) -> UnsafeMutableRawPointer {
    return FfiConverterTypeAlphaBumpDetector.lower(value)
}




/**
 * Calmness model
 */
public protocol CalmnessModelProtocol : AnyObject {
    
    func minSamples()  -> UInt32
    
    func name()  -> String
    
    func process(interleavedData: [Float]) throws  -> CalmnessResult?
    
    func reset() 
    
    func setSmoothing(alpha: Float) 
    
}

/**
 * Calmness model
 */
open class CalmnessModel:
    CalmnessModelProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_eeg_ffi_fn_clone_calmnessmodel(self.pointer, $0) }
    }
public convenience init(sampleRate: UInt16, channelCount: UInt32) {
    let pointer =
        try! rustCall() {
    uniffi_eeg_ffi_fn_constructor_calmnessmodel_new(
        FfiConverterUInt16.lower(sampleRate),
        FfiConverterUInt32.lower(channelCount),$0
    )
}
    self.init(unsafeFromRawPointer: pointer)
}

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_eeg_ffi_fn_free_calmnessmodel(pointer, $0) }
    }

    

    
open func minSamples() -> UInt32 {
    return try!  FfiConverterUInt32.lift(try! rustCall() {
    uniffi_eeg_ffi_fn_method_calmnessmodel_min_samples(self.uniffiClonePointer(),$0
    )
})
}
    
open func name() -> String {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_eeg_ffi_fn_method_calmnessmodel_name(self.uniffiClonePointer(),$0
    )
})
}
    
open func process(interleavedData: [Float])throws  -> CalmnessResult? {
    return try  FfiConverterOptionTypeCalmnessResult.lift(try rustCallWithError(FfiConverterTypeEegError.lift) {
    uniffi_eeg_ffi_fn_method_calmnessmodel_process(self.uniffiClonePointer(),
        FfiConverterSequenceFloat.lower(interleavedData),$0
    )
})
}
    
open func reset() {try! rustCall() {
    uniffi_eeg_ffi_fn_method_calmnessmodel_reset(self.uniffiClonePointer(),$0
    )
}
}
    
open func setSmoothing(alpha: Float) {try! rustCall() {
    uniffi_eeg_ffi_fn_method_calmnessmodel_set_smoothing(self.uniffiClonePointer(),
        FfiConverterFloat.lower(alpha),$0
    )
}
}
    

}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCalmnessModel: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = CalmnessModel

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> CalmnessModel {
        return CalmnessModel(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: CalmnessModel) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CalmnessModel {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: CalmnessModel, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCalmnessModel_lift(_ pointer: UnsafeMutableRawPointer) throws -> CalmnessModel {
    return try FfiConverterTypeCalmnessModel.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCalmnessModel_lower(_ value: CalmnessModel) -> UnsafeMutableRawPointer {
    return FfiConverterTypeCalmnessModel.lower(value)
}




/**
 * EEG frequency band definitions
 */
public protocol EegBandsProtocol : AnyObject {
    
    func getAlpha()  -> BandRange
    
    func getBeta()  -> BandRange
    
    func getDelta()  -> BandRange
    
    func getGamma()  -> BandRange
    
    func getTheta()  -> BandRange
    
}

/**
 * EEG frequency band definitions
 */
open class EegBands:
    EegBandsProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_eeg_ffi_fn_clone_eegbands(self.pointer, $0) }
    }
public convenience init() {
    let pointer =
        try! rustCall() {
    uniffi_eeg_ffi_fn_constructor_eegbands_new($0
    )
}
    self.init(unsafeFromRawPointer: pointer)
}

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_eeg_ffi_fn_free_eegbands(pointer, $0) }
    }

    

    
open func getAlpha() -> BandRange {
    return try!  FfiConverterTypeBandRange.lift(try! rustCall() {
    uniffi_eeg_ffi_fn_method_eegbands_get_alpha(self.uniffiClonePointer(),$0
    )
})
}
    
open func getBeta() -> BandRange {
    return try!  FfiConverterTypeBandRange.lift(try! rustCall() {
    uniffi_eeg_ffi_fn_method_eegbands_get_beta(self.uniffiClonePointer(),$0
    )
})
}
    
open func getDelta() -> BandRange {
    return try!  FfiConverterTypeBandRange.lift(try! rustCall() {
    uniffi_eeg_ffi_fn_method_eegbands_get_delta(self.uniffiClonePointer(),$0
    )
})
}
    
open func getGamma() -> BandRange {
    return try!  FfiConverterTypeBandRange.lift(try! rustCall() {
    uniffi_eeg_ffi_fn_method_eegbands_get_gamma(self.uniffiClonePointer(),$0
    )
})
}
    
open func getTheta() -> BandRange {
    return try!  FfiConverterTypeBandRange.lift(try! rustCall() {
    uniffi_eeg_ffi_fn_method_eegbands_get_theta(self.uniffiClonePointer(),$0
    )
})
}
    

}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeEegBands: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = EegBands

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> EegBands {
        return EegBands(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: EegBands) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> EegBands {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: EegBands, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEegBands_lift(_ pointer: UnsafeMutableRawPointer) throws -> EegBands {
    return try FfiConverterTypeEegBands.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEegBands_lower(_ value: EegBands) -> UnsafeMutableRawPointer {
    return FfiConverterTypeEegBands.lower(value)
}




/**
 * Signal processing functions
 */
public protocol SignalProcessorProtocol : AnyObject {
    
    func alphaPower(data: [Float]) throws  -> Float
    
    func betaPower(data: [Float]) throws  -> Float
    
    func computeBandPowers(data: [Float]) throws  -> BandPowers
    
    func customBandPower(data: [Float], lowFreq: Float, highFreq: Float) throws  -> Float
    
    func deltaPower(data: [Float]) throws  -> Float
    
    func fftFrequencies(sampleCount: UInt32)  -> [Float]
    
    func gammaPower(data: [Float]) throws  -> Float
    
    func powerSpectrum(data: [Float]) throws  -> [Float]
    
    func thetaPower(data: [Float]) throws  -> Float
    
}

/**
 * Signal processing functions
 */
open class SignalProcessor:
    SignalProcessorProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_eeg_ffi_fn_clone_signalprocessor(self.pointer, $0) }
    }
public convenience init(sampleRate: UInt16) {
    let pointer =
        try! rustCall() {
    uniffi_eeg_ffi_fn_constructor_signalprocessor_new(
        FfiConverterUInt16.lower(sampleRate),$0
    )
}
    self.init(unsafeFromRawPointer: pointer)
}

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_eeg_ffi_fn_free_signalprocessor(pointer, $0) }
    }

    

    
open func alphaPower(data: [Float])throws  -> Float {
    return try  FfiConverterFloat.lift(try rustCallWithError(FfiConverterTypeEegError.lift) {
    uniffi_eeg_ffi_fn_method_signalprocessor_alpha_power(self.uniffiClonePointer(),
        FfiConverterSequenceFloat.lower(data),$0
    )
})
}
    
open func betaPower(data: [Float])throws  -> Float {
    return try  FfiConverterFloat.lift(try rustCallWithError(FfiConverterTypeEegError.lift) {
    uniffi_eeg_ffi_fn_method_signalprocessor_beta_power(self.uniffiClonePointer(),
        FfiConverterSequenceFloat.lower(data),$0
    )
})
}
    
open func computeBandPowers(data: [Float])throws  -> BandPowers {
    return try  FfiConverterTypeBandPowers.lift(try rustCallWithError(FfiConverterTypeEegError.lift) {
    uniffi_eeg_ffi_fn_method_signalprocessor_compute_band_powers(self.uniffiClonePointer(),
        FfiConverterSequenceFloat.lower(data),$0
    )
})
}
    
open func customBandPower(data: [Float], lowFreq: Float, highFreq: Float)throws  -> Float {
    return try  FfiConverterFloat.lift(try rustCallWithError(FfiConverterTypeEegError.lift) {
    uniffi_eeg_ffi_fn_method_signalprocessor_custom_band_power(self.uniffiClonePointer(),
        FfiConverterSequenceFloat.lower(data),
        FfiConverterFloat.lower(lowFreq),
        FfiConverterFloat.lower(highFreq),$0
    )
})
}
    
open func deltaPower(data: [Float])throws  -> Float {
    return try  FfiConverterFloat.lift(try rustCallWithError(FfiConverterTypeEegError.lift) {
    uniffi_eeg_ffi_fn_method_signalprocessor_delta_power(self.uniffiClonePointer(),
        FfiConverterSequenceFloat.lower(data),$0
    )
})
}
    
open func fftFrequencies(sampleCount: UInt32) -> [Float] {
    return try!  FfiConverterSequenceFloat.lift(try! rustCall() {
    uniffi_eeg_ffi_fn_method_signalprocessor_fft_frequencies(self.uniffiClonePointer(),
        FfiConverterUInt32.lower(sampleCount),$0
    )
})
}
    
open func gammaPower(data: [Float])throws  -> Float {
    return try  FfiConverterFloat.lift(try rustCallWithError(FfiConverterTypeEegError.lift) {
    uniffi_eeg_ffi_fn_method_signalprocessor_gamma_power(self.uniffiClonePointer(),
        FfiConverterSequenceFloat.lower(data),$0
    )
})
}
    
open func powerSpectrum(data: [Float])throws  -> [Float] {
    return try  FfiConverterSequenceFloat.lift(try rustCallWithError(FfiConverterTypeEegError.lift) {
    uniffi_eeg_ffi_fn_method_signalprocessor_power_spectrum(self.uniffiClonePointer(),
        FfiConverterSequenceFloat.lower(data),$0
    )
})
}
    
open func thetaPower(data: [Float])throws  -> Float {
    return try  FfiConverterFloat.lift(try rustCallWithError(FfiConverterTypeEegError.lift) {
    uniffi_eeg_ffi_fn_method_signalprocessor_theta_power(self.uniffiClonePointer(),
        FfiConverterSequenceFloat.lower(data),$0
    )
})
}
    

}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSignalProcessor: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = SignalProcessor

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> SignalProcessor {
        return SignalProcessor(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: SignalProcessor) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SignalProcessor {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: SignalProcessor, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSignalProcessor_lift(_ pointer: UnsafeMutableRawPointer) throws -> SignalProcessor {
    return try FfiConverterTypeSignalProcessor.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSignalProcessor_lower(_ value: SignalProcessor) -> UnsafeMutableRawPointer {
    return FfiConverterTypeSignalProcessor.lower(value)
}


/**
 * Alpha bump detection result
 */
public struct AlphaBumpResult {
    public var state: AlphaState
    public var alphaPower: Float
    public var baseline: Float
    public var stateChanged: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(state: AlphaState, alphaPower: Float, baseline: Float, stateChanged: Bool) {
        self.state = state
        self.alphaPower = alphaPower
        self.baseline = baseline
        self.stateChanged = stateChanged
    }
}



extension AlphaBumpResult: Equatable, Hashable {
    public static func ==(lhs: AlphaBumpResult, rhs: AlphaBumpResult) -> Bool {
        if lhs.state != rhs.state {
            return false
        }
        if lhs.alphaPower != rhs.alphaPower {
            return false
        }
        if lhs.baseline != rhs.baseline {
            return false
        }
        if lhs.stateChanged != rhs.stateChanged {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(state)
        hasher.combine(alphaPower)
        hasher.combine(baseline)
        hasher.combine(stateChanged)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAlphaBumpResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AlphaBumpResult {
        return
            try AlphaBumpResult(
                state: FfiConverterTypeAlphaState.read(from: &buf), 
                alphaPower: FfiConverterFloat.read(from: &buf), 
                baseline: FfiConverterFloat.read(from: &buf), 
                stateChanged: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: AlphaBumpResult, into buf: inout [UInt8]) {
        FfiConverterTypeAlphaState.write(value.state, into: &buf)
        FfiConverterFloat.write(value.alphaPower, into: &buf)
        FfiConverterFloat.write(value.baseline, into: &buf)
        FfiConverterBool.write(value.stateChanged, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAlphaBumpResult_lift(_ buf: RustBuffer) throws -> AlphaBumpResult {
    return try FfiConverterTypeAlphaBumpResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAlphaBumpResult_lower(_ value: AlphaBumpResult) -> RustBuffer {
    return FfiConverterTypeAlphaBumpResult.lower(value)
}


/**
 * Band power results
 */
public struct BandPowers {
    public var delta: Float
    public var theta: Float
    public var alpha: Float
    public var beta: Float
    public var gamma: Float

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(delta: Float, theta: Float, alpha: Float, beta: Float, gamma: Float) {
        self.delta = delta
        self.theta = theta
        self.alpha = alpha
        self.beta = beta
        self.gamma = gamma
    }
}



extension BandPowers: Equatable, Hashable {
    public static func ==(lhs: BandPowers, rhs: BandPowers) -> Bool {
        if lhs.delta != rhs.delta {
            return false
        }
        if lhs.theta != rhs.theta {
            return false
        }
        if lhs.alpha != rhs.alpha {
            return false
        }
        if lhs.beta != rhs.beta {
            return false
        }
        if lhs.gamma != rhs.gamma {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(delta)
        hasher.combine(theta)
        hasher.combine(alpha)
        hasher.combine(beta)
        hasher.combine(gamma)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeBandPowers: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> BandPowers {
        return
            try BandPowers(
                delta: FfiConverterFloat.read(from: &buf), 
                theta: FfiConverterFloat.read(from: &buf), 
                alpha: FfiConverterFloat.read(from: &buf), 
                beta: FfiConverterFloat.read(from: &buf), 
                gamma: FfiConverterFloat.read(from: &buf)
        )
    }

    public static func write(_ value: BandPowers, into buf: inout [UInt8]) {
        FfiConverterFloat.write(value.delta, into: &buf)
        FfiConverterFloat.write(value.theta, into: &buf)
        FfiConverterFloat.write(value.alpha, into: &buf)
        FfiConverterFloat.write(value.beta, into: &buf)
        FfiConverterFloat.write(value.gamma, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBandPowers_lift(_ buf: RustBuffer) throws -> BandPowers {
    return try FfiConverterTypeBandPowers.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBandPowers_lower(_ value: BandPowers) -> RustBuffer {
    return FfiConverterTypeBandPowers.lower(value)
}


/**
 * Frequency band range
 */
public struct BandRange {
    public var low: Float
    public var high: Float

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(low: Float, high: Float) {
        self.low = low
        self.high = high
    }
}



extension BandRange: Equatable, Hashable {
    public static func ==(lhs: BandRange, rhs: BandRange) -> Bool {
        if lhs.low != rhs.low {
            return false
        }
        if lhs.high != rhs.high {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(low)
        hasher.combine(high)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeBandRange: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> BandRange {
        return
            try BandRange(
                low: FfiConverterFloat.read(from: &buf), 
                high: FfiConverterFloat.read(from: &buf)
        )
    }

    public static func write(_ value: BandRange, into buf: inout [UInt8]) {
        FfiConverterFloat.write(value.low, into: &buf)
        FfiConverterFloat.write(value.high, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBandRange_lift(_ buf: RustBuffer) throws -> BandRange {
    return try FfiConverterTypeBandRange.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBandRange_lower(_ value: BandRange) -> RustBuffer {
    return FfiConverterTypeBandRange.lower(value)
}


/**
 * Calmness model result
 */
public struct CalmnessResult {
    public var score: Float
    public var smoothedScore: Float
    public var alphaBetaRatio: Float
    public var alphaPower: Float
    public var betaPower: Float
    public var thetaPower: Float

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(score: Float, smoothedScore: Float, alphaBetaRatio: Float, alphaPower: Float, betaPower: Float, thetaPower: Float) {
        self.score = score
        self.smoothedScore = smoothedScore
        self.alphaBetaRatio = alphaBetaRatio
        self.alphaPower = alphaPower
        self.betaPower = betaPower
        self.thetaPower = thetaPower
    }
}



extension CalmnessResult: Equatable, Hashable {
    public static func ==(lhs: CalmnessResult, rhs: CalmnessResult) -> Bool {
        if lhs.score != rhs.score {
            return false
        }
        if lhs.smoothedScore != rhs.smoothedScore {
            return false
        }
        if lhs.alphaBetaRatio != rhs.alphaBetaRatio {
            return false
        }
        if lhs.alphaPower != rhs.alphaPower {
            return false
        }
        if lhs.betaPower != rhs.betaPower {
            return false
        }
        if lhs.thetaPower != rhs.thetaPower {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(score)
        hasher.combine(smoothedScore)
        hasher.combine(alphaBetaRatio)
        hasher.combine(alphaPower)
        hasher.combine(betaPower)
        hasher.combine(thetaPower)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCalmnessResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CalmnessResult {
        return
            try CalmnessResult(
                score: FfiConverterFloat.read(from: &buf), 
                smoothedScore: FfiConverterFloat.read(from: &buf), 
                alphaBetaRatio: FfiConverterFloat.read(from: &buf), 
                alphaPower: FfiConverterFloat.read(from: &buf), 
                betaPower: FfiConverterFloat.read(from: &buf), 
                thetaPower: FfiConverterFloat.read(from: &buf)
        )
    }

    public static func write(_ value: CalmnessResult, into buf: inout [UInt8]) {
        FfiConverterFloat.write(value.score, into: &buf)
        FfiConverterFloat.write(value.smoothedScore, into: &buf)
        FfiConverterFloat.write(value.alphaBetaRatio, into: &buf)
        FfiConverterFloat.write(value.alphaPower, into: &buf)
        FfiConverterFloat.write(value.betaPower, into: &buf)
        FfiConverterFloat.write(value.thetaPower, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCalmnessResult_lift(_ buf: RustBuffer) throws -> CalmnessResult {
    return try FfiConverterTypeCalmnessResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCalmnessResult_lower(_ value: CalmnessResult) -> RustBuffer {
    return FfiConverterTypeCalmnessResult.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Alpha state enum for FFI
 */

public enum AlphaState {
    
    case high
    case low
    case transitioning
    case unknown
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAlphaState: FfiConverterRustBuffer {
    typealias SwiftType = AlphaState

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AlphaState {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .high
        
        case 2: return .low
        
        case 3: return .transitioning
        
        case 4: return .unknown
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: AlphaState, into buf: inout [UInt8]) {
        switch value {
        
        
        case .high:
            writeInt(&buf, Int32(1))
        
        
        case .low:
            writeInt(&buf, Int32(2))
        
        
        case .transitioning:
            writeInt(&buf, Int32(3))
        
        
        case .unknown:
            writeInt(&buf, Int32(4))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAlphaState_lift(_ buf: RustBuffer) throws -> AlphaState {
    return try FfiConverterTypeAlphaState.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAlphaState_lower(_ value: AlphaState) -> RustBuffer {
    return FfiConverterTypeAlphaState.lower(value)
}



extension AlphaState: Equatable, Hashable {}




/**
 * Error types for FFI
 */
public enum EegError {

    
    
    case InvalidData
    case ProcessingError
    case NotEnoughSamples
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeEegError: FfiConverterRustBuffer {
    typealias SwiftType = EegError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> EegError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .InvalidData
        case 2: return .ProcessingError
        case 3: return .NotEnoughSamples

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: EegError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case .InvalidData:
            writeInt(&buf, Int32(1))
        
        
        case .ProcessingError:
            writeInt(&buf, Int32(2))
        
        
        case .NotEnoughSamples:
            writeInt(&buf, Int32(3))
        
        }
    }
}


extension EegError: Equatable, Hashable {}

extension EegError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeAlphaBumpResult: FfiConverterRustBuffer {
    typealias SwiftType = AlphaBumpResult?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeAlphaBumpResult.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeAlphaBumpResult.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeCalmnessResult: FfiConverterRustBuffer {
    typealias SwiftType = CalmnessResult?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeCalmnessResult.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeCalmnessResult.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceFloat: FfiConverterRustBuffer {
    typealias SwiftType = [Float]

    public static func write(_ value: [Float], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterFloat.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Float] {
        let len: Int32 = try readInt(&buf)
        var seq = [Float]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterFloat.read(from: &buf))
        }
        return seq
    }
}
/**
 * Get SDK version
 */
public func getVersion() -> String {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_eeg_ffi_fn_func_get_version($0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private var initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_eeg_ffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_eeg_ffi_checksum_func_get_version() != 26358) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_eeg_ffi_checksum_method_alphabumpdetector_min_samples() != 54686) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_eeg_ffi_checksum_method_alphabumpdetector_name() != 1833) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_eeg_ffi_checksum_method_alphabumpdetector_process() != 26167) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_eeg_ffi_checksum_method_alphabumpdetector_reset() != 11586) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_eeg_ffi_checksum_method_alphabumpdetector_set_baseline_smoothing() != 34337) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_eeg_ffi_checksum_method_alphabumpdetector_set_threshold() != 32825) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_eeg_ffi_checksum_method_calmnessmodel_min_samples() != 26933) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_eeg_ffi_checksum_method_calmnessmodel_name() != 15583) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_eeg_ffi_checksum_method_calmnessmodel_process() != 13525) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_eeg_ffi_checksum_method_calmnessmodel_reset() != 46985) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_eeg_ffi_checksum_method_calmnessmodel_set_smoothing() != 9347) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_eeg_ffi_checksum_method_eegbands_get_alpha() != 24093) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_eeg_ffi_checksum_method_eegbands_get_beta() != 56036) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_eeg_ffi_checksum_method_eegbands_get_delta() != 24064) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_eeg_ffi_checksum_method_eegbands_get_gamma() != 35343) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_eeg_ffi_checksum_method_eegbands_get_theta() != 9262) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_eeg_ffi_checksum_method_signalprocessor_alpha_power() != 42616) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_eeg_ffi_checksum_method_signalprocessor_beta_power() != 40801) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_eeg_ffi_checksum_method_signalprocessor_compute_band_powers() != 21815) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_eeg_ffi_checksum_method_signalprocessor_custom_band_power() != 35331) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_eeg_ffi_checksum_method_signalprocessor_delta_power() != 63638) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_eeg_ffi_checksum_method_signalprocessor_fft_frequencies() != 55775) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_eeg_ffi_checksum_method_signalprocessor_gamma_power() != 51602) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_eeg_ffi_checksum_method_signalprocessor_power_spectrum() != 95) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_eeg_ffi_checksum_method_signalprocessor_theta_power() != 25731) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_eeg_ffi_checksum_constructor_alphabumpdetector_new() != 38609) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_eeg_ffi_checksum_constructor_calmnessmodel_new() != 1031) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_eeg_ffi_checksum_constructor_eegbands_new() != 26861) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_eeg_ffi_checksum_constructor_signalprocessor_new() != 25523) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all